### ISSUE TITLE
[BUG] App crashes when trying to obtain Period

### ISSUE THREAD

**Issue by pgallardor** [alercebroker/web-services#249]
```
Traceback (most recent call last):
  File "/app/src/database/sql.py", line 29, in session
    yield session
  File "/app/src/core/service.py", line 415, in _get_period_sql
    return Success(result[0])
                   ~~~~~~^^^
IndexError: list index out of range
ERROR:root:list index out of range
INFO:     190.47.70.159:0 - "GET /htmx/lightcurve?oid=ZTF20aaelulu&survey=ztf HTTP/1.0" 500 Internal Server Error

**Comment by dirodriguezm** [comment]
Si no está corregido el objeto o no tiene calculado el periodo, no se muestra el gráfico folded
